# Generated by Django 3.0.8 on 2021-01-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cimal',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
