# Generated by Django 3.0.8 on 2021-01-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210104_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cimal',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
